---
<h1><center>  lab 4 : Text Vectorization - Part 1 </center>
    
<img src="https://lh6.googleusercontent.com/GTmNOZ5DkSorxEoATI93xvrBDCCOn0XAGDav8ybPJ0hIkqlk4nimcY9P8SNleZV1Cf8vnGVAlwawdZ5Fe8kPykKRZbHVUixjSPu1BJdd9DoAdgAVr5VMwhK2oSkXpyDFXunuON-l" width="500">

>```Created by Jinnie Shin (jinnie.shin@coe.ufl.edu)```\
>```Date: ```
---

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmNf86oJnfhpkPA9LnrFnAbfwF2VywPYpB_w&usqp=CAU" align="left" width="70" height="70" align="left">

### Required Packages or Dependencies

In [ ]:
#!pip install nbimporter #run this if you run into an error (download nbimporter)
import pandas as pd
import numpy as np
import nltk
nltk.download(['punkt', 'wordnet', 'omw-1.4'])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True


## **REVIEW**: Dataset

> Using the text_normalizer function we created last time, we will import `essay set 2`

In [ ]:
class text_normalize():

    def import_data(self, essay_set=3):
        import numpy as np
        import pandas as pd
        self.essay_set = essay_set
        self.data = []
        self.score = []
        filename = 'training_set_rel3.xlsx'
        data = pd.read_excel(filename)
        self.data  = data[data['essay_set']==self.essay_set].essay.values
        self.score = data[data['essay_set']==self.essay_set].domain1_score.values

        return [' '.join(i) for i in self.data], pd.DataFrame(list(zip(self.data, self.score)), columns=['response', 'score'])

    def cleaning(self, string):
        import re
        string  = string.lower() # step 1. lowercase

        punc = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' # step 2. remove punctuations
        string  = string.strip(punc)

        string  = string.replace("can't", 'cannot') # step 3. replace abbreviated forms
        string = string.replace("n't", ' not')
        string  = string.replace("'ll", ' will')
        string  = string.replace("'m", ' am')
        string = string.replace("he's", "he is")
        string = string.replace("it's", 'it is')

        return re.sub(r"\d+", "<DIGIT>", string) # step 4. replace all the numbers to <DIGIT>

    def sent_tokenize(self, string):
        import nltk
        return nltk.sent_tokenize(string)

    def tokenize(self, string):
        import nltk
        return nltk.word_tokenize(string)

    def stemming(self, tokens):
        import nltk
        stemmer = nltk.stem.PorterStemmer()
        return [stemmer.stem(token) for token in tokens]

    def lemmatize(self, tokens):
        import nltk
        lemmatizer = nltk.stem.WordNetLemmatizer()
        return [lemmatizer.lemmatize(token) for token in tokens]

    def preprocess(self, essay_set=1):
        _, self.df = self.import_data(essay_set=essay_set)
        self.df['tokens'] = self.df.response.apply(self.tokenize)
        self.df['sentences'] = self.df.response.apply(self.sent_tokenize)
        self.df['stem'] = self.df.tokens.apply(self.stemming)
        self.df['lemma'] = self.df.tokens.apply(self.lemmatize)

        return self.df

normalizer = text_normalize() # call the text_normalize function and name it normalizer

df = normalizer.preprocess(3)

In [ ]:
df

,response,score,tokens,sentences,stem,lemma
0,The features of the setting affect the cyclist...,1.0,"[The, features, of, the, setting, affect, the,...",[The features of the setting affect the cyclis...,"[the, featur, of, the, set, affect, the, cycli...","[The, feature, of, the, setting, affect, the, ..."
1,The features of the setting affected the cycli...,2.0,"[The, features, of, the, setting, affected, th...",[The features of the setting affected the cycl...,"[the, featur, of, the, set, affect, the, cycli...","[The, feature, of, the, setting, affected, the..."
2,Everyone travels to unfamiliar places. Sometim...,1.0,"[Everyone, travels, to, unfamiliar, places, .,...","[Everyone travels to unfamiliar places., Somet...","[everyon, travel, to, unfamiliar, place, ., so...","[Everyone, travel, to, unfamiliar, place, ., S..."
3,I believe the features of the cyclist affected...,1.0,"[I, believe, the, features, of, the, cyclist, ...",[I believe the features of the cyclist affecte...,"[i, believ, the, featur, of, the, cyclist, aff...","[I, believe, the, feature, of, the, cyclist, a..."
4,The setting effects the cyclist because of the...,2.0,"[The, setting, effects, the, cyclist, because,...",[The setting effects the cyclist because of th...,"[the, set, effect, the, cyclist, becaus, of, t...","[The, setting, effect, the, cyclist, because, ..."
...,...,...,...,...,...,...
1721,"In the story, the setting affected the cyclist...",2.0,"[In, the, story, ,, the, setting, affected, th...","[In the story, the setting affected the cyclis...","[in, the, stori, ,, the, set, affect, the, cyc...","[In, the, story, ,, the, setting, affected, th..."
1722,The features of the setting affect the cyclist...,1.0,"[The, features, of, the, setting, affect, the,...",[The features of the setting affect the cyclis...,"[the, featur, of, the, set, affect, the, cycli...","[The, feature, of, the, setting, affect, the, ..."
1723,The setting greatly affects the cyclist trying...,2.0,"[The, setting, greatly, affects, the, cyclist,...",[The setting greatly affects the cyclist tryin...,"[the, set, greatli, affect, the, cyclist, tri,...","[The, setting, greatly, affect, the, cyclist, ..."
1724,The features of the setting affected the cycli...,2.0,"[The, features, of, the, setting, affected, th...",[The features of the setting affected the cycl...,"[the, featur, of, the, set, affect, the, cycli...","[The, feature, of, the, setting, affected, the..."
1725,The features of the setting in “Rough Road Ahe...,3.0,"[The, features, of, the, setting, in, “, Rough...",[The features of the setting in “Rough Road Ah...,"[the, featur, of, the, set, in, “, rough, road...","[The, feature, of, the, setting, in, “, Rough,..."

### Alternative (easier) Option

In [ ]:
# the goal is to preprocess the data using the following three functions (tokenization, stemming, and lemmatization)
def tokenize(sentence, sent='False'):
    if sent=='True':
        return [nltk.word_tokenize(i) for i in nltk.sent_tokenize(sentence)]
    elif sent=='False':
        return nltk.word_tokenize(sentence)

def stemming(token_lst):
    stemmer = nltk.stem.PorterStemmer()
    return [stemmer.stem(token) for token in token_lst]

def lemmatize(token_lst):
    lemmatizer = nltk.stem.WordNetLemmatizer()
    return [lemmatizer.lemmatize(token) for token in token_lst]

def cleaning(string):

    import re
    string = string.lower() # step 1. lowercase

    punc = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~' # step 2. remove punctuations
    string = string.strip(punc)

    string = string.replace("can't", 'cannot') # step 3. replace abbreviated forms
    string = string.replace("n't", ' not')
    string = string.replace("'ll", ' will')
    string = string.replace("'m", ' am')
    string = string.replace("he's", "he is")
    string = string.replace("it's", 'it is')

    string = re.sub(r"\d+", "<DIGIT>", string) # step 4. replace all the numbers to <DIGIT>

    return string

############## YOU CODE HERE ################
'''
You can also manually apply these functions to your text data
'''

filename = 'training_set_rel3.xlsx'
data = pd.read_excel(filename)
data = data[data.essay_set==3]
data['essay'].apply(cleaning).apply(tokenize).apply(stemming).apply(lemmatize)


## 1. Text Vectorization
### 1.1 Term-Document Matrix

In [ ]:
# Our goal is to use the output we created above ("cleaned" column) to create a term-document matrix
# Let's take a look at this additional function we can use "Counter"

from collections import Counter

print(Counter([1,2,2,3,3,3,4,4,4,4])) # Counts the unique element in the given list

print(Counter(['apple', 'apple', 'pear', 'pear', 'pear']+['cherry']*5))

Counter({4: 4, 3: 3, 2: 2, 1: 1})
Counter({'cherry': 5, 'pear': 3, 'apple': 2})

> Let's create a function called `count_vectorizer`, which takes a dataframe (`data`) as an input and produce `bow` and `unique_vocabulary` as the outputs.

In [ ]:

def count_vectorizer(dataframe, column='tokens'): #Input is the dataframe we created above with three columns

    from collections import Counter # import the Counter function

    dataframe[column] = dataframe[column].apply(Counter).apply(dict) #we apply the counter function to the "cleaned" columns
                                                                          # we used the apply function in week 2

    bow = pd.DataFrame(dataframe[column].tolist()).T.fillna(0) # we restructure the output as a dataframe and name it "bow"
                                                                  # also fill in the missing values (nan -> 0 )
    unique_vocab = list(bow.index)                                # FYI, bow standards for (bag-of-words)

    return bow, unique_vocab

bow, unique_vocab = count_vectorizer(df, 'stem')
print(bow)
print(unique_vocab)

,0,1,2,3,4,5,6,7,8,9,...,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725
the,8.0,19.0,5.0,8.0,17.0,7.0,3.0,6.0,8.0,11.0,...,10.0,9.0,0.0,12.0,14.0,7.0,4.0,10.0,13.0,11.0
featur,2.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,3.0,1.0,0.0,1.0,0.0,1.0,1.0
of,4.0,4.0,0.0,6.0,8.0,3.0,0.0,5.0,2.0,2.0,...,7.0,2.0,1.0,4.0,3.0,2.0,2.0,4.0,2.0,4.0
set,2.0,1.0,1.0,0.0,4.0,2.0,0.0,0.0,2.0,0.0,...,1.0,0.0,0.0,3.0,1.0,1.0,1.0,2.0,2.0,2.0
affect,2.0,2.0,1.0,1.0,0.0,1.0,0.0,3.0,1.0,2.0,...,2.0,0.0,0.0,2.0,1.0,1.0,1.0,3.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
california…,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
evidenc,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
goup,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
hills…,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
seveal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0



> *Let's explore!*

In [ ]:
# the most frequent word?

### 1.2. Term-Frequency Inverse Documenr-Frequency Matrix

       > Term-Freqeuncy: tf(t,d) = log(count(t,d)+1)
       > Inverse-Document Frequency: idf(t) = log(N/df(t))
       > TF-IDF: tf(t,d) X idf(t)

In [ ]:
def tfidf_vectorizer(bow):

    # ======================== STEP 1 ============================ #

    # Step 1: we will compute the term-frequency (TF)

    for response in bow.columns:
        bow[response] = bow[response].apply(lambda x: np.log10(x+1))

    step1_output = bow

    # ======================== STEP 2 ============================ #

    # Step 2: we will compute the inverse-document frequency (IDF)

    df = pd.DataFrame( ( ( bow > 0 ) * 1 ).sum(axis=1), columns=['df'] )  #this is the document-freqeuncy
    N = bow.shape[1] # this is the collection frequency (total number of doucments)
    df['IDF'] = df['df'].apply(lambda x: np.log10(N/x))
    step2_output= df

    # ======================== STEP 3 ============================ #

    # Step 3: term-freqeuncy (TF) * inverse-document frequency (IDF) = TF-IDF

    tfidf = bow.multiply(df.IDF, axis='index')

    return tfidf, step1_output, step2_output

> *Let's explore!*

In [ ]:
tfidf, _, _ = tfidf_vectorizer(bow)

In [ ]:
tfidf

,0,1,2,3,4,5,6,7,8,9,...,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725
the,0.000882,0.001097,0.000757,0.000882,0.001070,0.000847,0.00062,0.000806,0.000882,0.000963,...,0.000939,0.000912,0.000000,0.000985,0.001023,0.000847,0.000697,0.000939,0.001005,0.000963
featur,0.044321,0.029899,0.000000,0.029899,0.000000,0.053546,0.00000,0.000000,0.000000,0.000000,...,0.029899,0.000000,0.000000,0.053546,0.029899,0.000000,0.029899,0.000000,0.029899,0.029899
of,0.010687,0.010687,0.000000,0.012351,0.013510,0.009503,0.00000,0.011606,0.007866,0.007866,...,0.012975,0.007866,0.005306,0.010687,0.009503,0.007866,0.007866,0.010687,0.007866,0.010687
set,0.016461,0.011104,0.011104,0.000000,0.022365,0.016461,0.00000,0.000000,0.016461,0.000000,...,0.011104,0.000000,0.000000,0.019887,0.011104,0.011104,0.011104,0.016461,0.016461,0.016461
affect,0.027669,0.027669,0.018666,0.018666,0.000000,0.018666,0.00000,0.033429,0.018666,0.027669,...,0.027669,0.000000,0.000000,0.027669,0.018666,0.018666,0.018666,0.033429,0.027669,0.018666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
california…,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.369953,0.000000,0.000000,0.000000,0.000000,0.000000
evidenc,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.369953,0.000000,0.000000,0.000000,0.000000,0.000000
goup,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.369953,0.000000,0.000000,0.000000
hills…,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.369953,0.000000
seveal,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.369953,0.000000

### Shortcut (You can use this for your project)

In [ ]:
!pip install scikit-learn

###### Count vectorizer #######
from sklearn.feature_extraction.text import CountVectorizer
#https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

vectorizer = CountVectorizer() # define the vectorizer function

input = df.response.values
print(input[:3])
X = vectorizer.fit_transform(input) # fit the data - the input is a list of string (list of essays)

print(X.toarray())
print(vectorizer.get_feature_names_out()) # this will print out the terms
print(X.toarray().shape)

############ TF-IDF #################
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(input)

print(X.toarray())
print(vectorizer.get_feature_names_out()) # this will print out the terms
print(X.toarray().shape)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.21.6)
['The features of the setting affect the cyclist in many ways. The features of the setting that affect the cyclist is the lact of information on were to go and the lack of water. This was a problem because he needed water for his trip and directions on were to go.  '
 'The features of the setting affected the cyclist in a negative way. He was in the desert, which is dry and hot. “I was traveling through the high deserts of California in June."(Kurmaskie @NUM1). Also, the  temperature was hot and made every thing around him hot, “brackish water faling somewhere in the neighborhood of two hundred degrees" (Kurmaskie @NUM1). Since he was in the desert, there was no escape from the sun. The text  states, “The sun was beginning to beat down”(Kurmaskie @NUM3). The cyclist was all alone in the road with none around him either so into he passed out, no one could help him. “ and the growing realization that I could drop from heatstroke on a gorgous day in June”(Kurmaskie @NUM1). "About forty miles into the pedal, I arrived at the first ‘town’ but on that morning it fit the traditional definition of a ghost town." (Kurmaskie @NUM3). Thesettings that the cyclist was riding in wasn\'t good ones and so they negativly affected him; causing him to be dehydrated and tiredin the end.'
 'Everyone travels to unfamiliar places. Sometimes we get lost and ask locals for directions which @MONTH1 not be a good idea. The setting affected the cyclist. He had a perfectly good map but asked older men who look like they haven’t been out in ages. The old men apparently haven’t been out because they gave the cyclist the wrong directions.  My advice would be to not listen to anyone no matter their age if you have a perfectly good map with you. Also try to know where you are going at all times. “Yes, sir!']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['12' '55' 'aase' ... 'yuuth' 'zone' 'zoo']
(1726, 6348)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['12' '55' 'aase' ... 'yuuth' 'zone' 'zoo']
(1726, 6348)

## 2. Text Similarity

<img src="https://i.pinimg.com/736x/2e/aa/7d/2eaa7d5021ca7c3c98bc93b98b9646fe.jpg" align="left" width="70" height="70" align="left">

> ## Task 1: Text Similarity

> The function below (`compare_similarity`) takes in the dataframe (`data`) as an input then computes the average cosine similarity between all pairs of documents in the dataframe. You can specify the type of the matrix you want to use to compute the similarity as well (`types: {'bow', 'tfidf'}`). For example, we can do `compare_similarty(data, types='bow')`
>> Q1. Let's randomly sample 10 documents from each score category (0 to 3) and compare the average similarity for the following two vectorization approaches. Then, explain the findings briefly.
>> - `BOW [score 0:       score 1:        score 2:          score 3:       ]`
>> - `TF-IDF [score 0:       score 1:        score 2:          score 3:       ]`

In [ ]:
def cosine_similarity(v1, v2):
    import math
    "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"

    sumxx, sumxy, sumyy = 0, 0, 0

    for i in range(len(v1)):
        x = v1[i]; y = v2[i]
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y

    return sumxy/math.sqrt(sumxx*sumyy)

def compare_similarity(matrix, types='bow'):

    if types=='bow':
        bow, _ = count_vectorizer(matrix)
        final = bow
    elif types=='tfidf':
        bow, _ = count_vectorizer(matrix)
        tfidf, _, _ = tfidf_vectorizer(bow)
        final = tfidf
    else:
        print('we will use the default==bow')
        bow, _ = count_vectorizer(matrix)
        final = bow

    from itertools import combinations
    sim = 0
    combi = list(combinations(list(final.columns), 2))
    for (i,j) in combi:
        temp = cosine_similarity(final[i].T, final[j].T)
        sim +=temp
    ave_sim = sim/len(combi)
    return ave_sim

In [ ]:
##################### YOUR CODE HERE ##############################

# Average cosine similarity between the randomly sampled 10 documents in the score category 0 (using BOW)
# step 1
score0 = df[df.score==0] #select the data from the score category 0
# step 2
random0 = score0.sample(10) # we are using the `df.sample(n)` function to randomly sample a total of N rows.
# step 3
compare_similarity(random0) # get the average similarity score

# Average cosine similarity between the randomly sampled 10 documents in the score category 1 (using BOW)


# Average cosine similarity between the randomly sampled 10 documents in the score category 2 (using BOW)


# Average cosine similarity between the randomly sampled 10 documents in the score category 3 (using BOW)



###################################################################

0.31662083985533535

In [ ]:
##################### YOUR CODE HERE ##############################

# Average cosine similarity between the randomly sampled 10 documents in the score category 0 (using TF-IDF)


# Average cosine similarity between the randomly sampled 10 documents in the score category 1 (using TF-IDF)


# Average cosine similarity between the randomly sampled 10 documents in the score category 2 (using TF-IDF)


# Average cosine similarity between the randomly sampled 10 documents in the score category 3 (using TF-IDF)



###################################################################